name: CI

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Person Detection with Camera Streaming

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build
        run: |
          make download
          curl -Ls -f https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/releases/download/arc-2020.09-release/arc_gnu_2020.09_prebuilt_elf32_le_linux_install.tar.gz -o arc_gnu.zip
          tar xf arc_gnu.zip
          export PATH=/home/runner/work/himax_tflm/himax_tflm/arc_gnu_2020.09_prebuilt_elf32_le_linux_install/bin:$PATH
          make person_detection_int8
          make flash example=person_detection_int8

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v3
        with:
          name: person_detection_camera
          path: "*.img"
          if-no-files-found: error
